FROM ruby:3.4.2
RUN apt-get update -qq && \
    apt-get install -y imagemagick && \
    apt-get install -y graphviz && \
    apt-get install -y vim

RUN mkdir /myapp
WORKDIR /myapp
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
COPY . /myapp
